# Generated by Django 3.1.4 on 2021-03-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, help_text='Updated At:', verbose_name='update date')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, help_text='Created At:', verbose_name='create date')),
                ('Ad_title', models.CharField(default='null', help_text='TITLE:', max_length=50, verbose_name='Ad about:')),
                ('Ad_details', models.TextField(help_text='DETAILS:', max_length=500, verbose_name='Ad details:')),
                ('category', models.CharField(help_text='Choose Category:', max_length=30, verbose_name='category')),
                ('photo', models.ImageField(upload_to='post/')),
                ('term', models.IntegerField(choices=[(24, 'day'), (48, 'tow days'), (72, 'three days')], help_text='publish for:', verbose_name='publish for')),
                ('approved', models.BooleanField(blank=True, default=False, help_text='is it approved', verbose_name='is it approved')),
                ('valid', models.BooleanField(blank=True, default=True, help_text='is it valid', verbose_name='is it valid')),
                ('publish_date', models.DateTimeField(blank=True, help_text='publish At:', null=True, verbose_name='publish At')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='AD_likes', to=settings.AUTH_USER_MODEL, verbose_name='like')),
                ('user', models.ForeignKey(help_text='User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adder', to=settings.AUTH_USER_MODEL, verbose_name='User:')),
            ],
            options={
                'verbose_name': 'AD',
                'verbose_name_plural': 'ADS',
            },
        ),
    ]
