# Generated by Django 3.1.4 on 2021-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(help_text='Choose Category:', max_length=30, verbose_name='category'),
        ),
    ]
